### ISSUE TITLE
No way to pull more than 2500 records

### ISSUE THREAD

**Issue by eugenejscray** [salesforce-marketingcloud/FuelSDK-Node-SOAP#106]
We need a way to pass the variable "Continue Request" to grab the next 2500 results.

**Comment by tdsticks** [comment]
Jamie Robertson has this working.  See the Files changed. 
https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/pull/68

I managed get this working on my end as well.

**Comment by eugenejscray** [comment]
Why hasnt this been merged yet?

**Comment by vernak2539** [comment]
@eugenejscray this has not been merged for a few reasons. 

1. There are JSHint errors 
    * While I understand the reasoning behind the author not wanting to do it a certain way, I will no be changing these rules. PRs will need to pass linting before merging
2. The test is not written properly and does not get executed when the test command is run via npm
    * There is a convention for this repo and it needs to be followed (use mocha and put it in the tests/specs folder)
3. There are now merge conflicts since feedback was not taken and actioned upon in a decent amount of time

Sorry if that's not what you wanted to hear. I've been prompt in providing feedback, but nothing has been updated.

**Comment by vernak2539** [comment]
continue request should be now provided in [v1.6.0](https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/releases/tag/1.6.0)

**Comment by kishore-indraganti** [comment]
```
const options = {
    Name: 'STG_Test3', //Dataextension name
    props: ['ID', 'BlogID'],
    filter: { //remove filter for all.
        leftOperand: 'ID',
        operator: 'greaterThan',
        rightOperand: 3000
    },
    continueRequest: true
};

const de = IET_Client.dataExtensionRow(options);

const test = de.get((err, response) => {
    if (err) {
        console.log(`Error in DE get method: ${JSON.stringify(err)}`);
    } else {
        console.log(JSON.stringify(response, null, '\t'));
    }
});
```

What I am doing here, I am getting only 2500 records on each call, how can i get next set of records

**Comment by danieldrasdo** [comment]
Hey @kishore-indraganti, did you ever get this to work? I'd love to see a working sample, thanks.
