### ISSUE TITLE
Token Expired issues

### ISSUE THREAD

**Issue by robin-chilliapple** [salesforce-marketingcloud/FuelSDK-Node-SOAP#112]
When SOAP request is running and instantly token is expired then my SOAP request is failed. I need some suggestion which automatically generate new access token if this expired. without single point of SOAP request failure. 

Please provide me fix of this issue with an example.

Thanks in advance.

**Comment by vernak2539** [comment]
Have you tried https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/blob/master/lib/fuel-soap.js#L65?

**Comment by robin-chilliapple** [comment]
Sorry ! It's not resolving my issues. It's give again and again token expired error. may be i am not using as right way. 
can you please provide me an example for this?

**Comment by vernak2539** [comment]
Quick question, was the token ever valid? seems more likely than it expiring right off the bat

**Comment by robin-chilliapple** [comment]
I have fixed that. This issue related Fuel-Auth node module. 
can i fix it on your Fuel-Auth module.

**Comment by vernak2539** [comment]
@robin-chilliapple thanks, please open a PR there. Will be closing this for now
