### ISSUE TITLE
Any workaround for Schedule method?

### ISSUE THREAD

**Issue by sovand** [salesforce-marketingcloud/FuelSDK-Node-SOAP#122]
The Schedule method is not yet implemented. Is there any workaround for that?
Thanks.

**Comment by DougMidgley** [comment]
Hi @sovand, please let me know thoughts :) I needed it too so may as well share

**Comment by sovand** [comment]
Hi @dougMidgley, I will add the code snippet tomorrow once I get to sit behind my laptop. Thanks.

**Comment by sovand** [comment]
@DougMidgley , sorry I forgot. I needed to have the schedule method and I extended the method this way, which worked for me.

`var FuelSoap = require('fuel-soap');
var isEmpty = require('lodash.isempty');

FuelSoap.prototype.schedule = function(type, props, options, callback) {
	var body;
	var optionsAndCallback;

	optionsAndCallback = determineCallbackAndOptions(arguments, callback, options);
	callback = optionsAndCallback.callback;
	options = optionsAndCallback.options;

	updateQueryAllAccounts = configureQueryAllAccounts(options);
	if(isEmpty(options)) {
		options = null;
	}

	body = {
		ScheduleRequestMsg: {
			$: {
				xmlns: 'http://exacttarget.com/wsdl/partnerAPI'
			}
			,
			"Action":"start",
			"Interactions": [{
				"Interaction": props.Interaction,
			}],
			"Schedule": options.Schedule
		}
	};

	body.ScheduleRequestMsg.Interactions[0].Interaction.$ = { 'xsi:type': 'q2:' + type, 'xmlns:q2': 'http://exacttarget.com/wsdl/partnerAPI' };

	this.soapRequest({
		action: 'Schedule'
		, req: body
		, key: 'ScheduleResponseMsg'
		, retry: true
	}, callback);
};

determineCallbackAndOptions = function(args, callback, options) {
	if(args.length < 4) {
		//if options are not included
		if(typeof args[2] === 'function') {
			callback = options;
			options = null;
		}
	}

	return {
		callback: callback
		, options: options
	};
}

configureQueryAllAccounts = function(options) {
	var addQueryAllAccounts = false;

	if(options && options.queryAllAccounts) {
		addQueryAllAccounts = true;
		delete options.queryAllAccounts;
	}

	return function(rootElement, child) {
		if(addQueryAllAccounts) {
			rootElement[child] = rootElement[child] || {};
			rootElement[child].QueryAllAccounts = true;
		}
	};
}

module.exports = FuelSoap;
`
