### ISSUE TITLE
Retrieve call is overly simple

### ISSUE THREAD

**Issue by aydrian** [salesforce-marketingcloud/FuelSDK-Node-SOAP#28]
We should look at expanding the retrieve call. Currently we accept type, fields to return, and a filter. We need to support getting more results if "MoreDataAvailable" is returned. There is also ClientIDs, QueryAllAccounts, and Retrieve Options and some others. It would be nice to get a better function signature in place before we release this to the world.

Open to suggestions.

**Comment by JamieRobertson** [comment]
@jamisonr 
Did you get anywhere with adding support for RetrieveAllSinceLastBatch and ContinueRequest?
It would be amazing if you have - if not I might give it a go

**Comment by vernak2539** [comment]
@JamieRobertson I don't think there has been much work. Would be lovely if you wanted to take a go

**Comment by JamieRobertson** [comment]
Hey, ye I added a bit of stuff, I will fork on Sunday and show what I've done. What I added is quite simple but I guess it's a start 

---- Alex Vernacchia wrote ----
