### ISSUE TITLE
Is it possible to make a PerformRequest?

### ISSUE THREAD

**Issue by batesy** [salesforce-marketingcloud/FuelSDK-Node-SOAP#67]
I ma trying to execute an email send, but the .perform() method doesn't seem to do anything. I am able to retrieve the email's SendDefinition, but can't figure out how to actually execute the send. Can you please provide an example?

**Comment by vernak2539** [comment]
Hey @batesy, it doesn't look as if that has been implemented at the moment. 

I'm not as familiar with the SOAP API as much as I am with the others, but maybe you'd want to checkout some of the things in [this library](https://github.com/salesforce-marketingcloud/FuelSDK-Node), which uses the SOAP module. Maybe it has an example or maybe [code@](https://code.exacttarget.com/) does

**Comment by tdsticks** [comment]
@batesy, please see my comment here: https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/issues/103 this may help.

**Comment by vernak2539** [comment]
It was implemented in https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/pull/108 (v1.5.0)
