### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by waysay** [salesforce-marketingcloud/FuelSDK-Node-SOAP#71]
Adding 

`requestOptions.rejectUnauthorized = false;`

after line 106 in lib/fuel-soap.js fixed what appears to be a certificate issue at the service.

**Comment by vernak2539** [comment]
please see https://github.com/salesforce-marketingcloud/FuelSDK-Node-SOAP/issues/66
